--BORRADO DE TABLAS

DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE PALET CASCADE CONSTRAINTS;
DROP TABLE PROMOCION CASCADE CONSTRAINTS;
DROP TABLE PEDIDO CASCADE CONSTRAINTS;
DROP TABLE CAMION CASCADE CONSTRAINTS;
DROP TABLE PUNTODEVENTA CASCADE CONSTRAINTS;
DROP TABLE CAMIONESPUNTODEVENTA CASCADE CONSTRAINTS;
DROP TABLE CAMIONESPEDIDO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOPALET CASCADE CONSTRAINTS;
DROP TABLE PALETPEDIDO CASCADE CONSTRAINTS;



--BORRADO DE SECUENCIAS 
DROP SEQUENCE SEC_PALET;
DROP SEQUENCE SEC_PEDIDO;
DROP SEQUENCE SEC_PRODUCTO;
DROP SEQUENCE SEC_PROMOCION;
DROP SEQUENCE SEC_PUNTODEVENTA;
DROP SEQUENCE SEC_INTERMEDIA;
DROP SEQUENCE SEC_INTER2;
DROP SEQUENCE SEC_INTER3;
DROP SEQUENCE SEC_INTER4;

--CREACIÓN DE TABLAS

CREATE TABLE PERSONAL(
DNI VARCHAR2(20)NOT NULL,
NOMBRE VARCHAR2(20)NOT NULL,
APELLIDOS VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(30),
TELEFONO NUMBER,
PRIMARY KEY(DNI));


CREATE TABLE PRODUCTO(
OID_PRODUCTO NUMBER NOT NULL,
TIPOMARCA VARCHAR2(20),
TIPOFORMATO VARCHAR2(20),
PRECIO NUMBER,
CONSTRAINT   CHECKMARCA CHECK (TIPOMARCA='HEINEKEN' OR TIPOMARCA='CRUZCAMPO' OR TIPOMARCA='DESPERADOS' OR TIPOMARCA='AMSTEL'),
CONSTRAINT CHECKFORMATO CHECK(TIPOFORMATO='LATA' OR TIPOFORMATO='BOTELLIN 1/5' OR TIPOFORMATO='BOTELLIN 1/3' OR TIPOFORMATO='LITRONA'),
PRIMARY KEY(OID_PRODUCTO));

CREATE TABLE PALET(
OID_PALET NUMBER NOT NULL,
PRIMARY KEY(OID_PALET));

CREATE TABLE PROMOCION(
OID_PROMOCION NUMBER,
TIPOPROMO VARCHAR2(20), 
FECHAINICIOP DATE,
FECHAFINP DATE, 
CONSTRAINT CHECKPROMO CHECK (TIPOPROMO='CRUZADA' OR TIPOPROMO='VALORAÑADIDO' OR TIPOPROMO='OFERTA' OR TIPOPROMO='NULA'), 
PRIMARY KEY(OID_PROMOCION));

CREATE TABLE PEDIDO(
OID_PEDIDO NUMBER NOT NULL,
OID_PROMOCION NUMBER,
FECHAPEDIDO DATE,
FECHAENTREGA DATE,
TIPODESCUENTO VARCHAR2(20),
ESTADO VARCHAR2(20),
CONSTRAINT CHECKDESCUENTO CHECK( TIPODESCUENTO='CAMION LLENO' OR TIPODESCUENTO='PRONTO PAGO' OR TIPODESCUENTO='NULL'),
PRIMARY KEY(OID_PEDIDO),
FOREIGN KEY(OID_PROMOCION) REFERENCES PROMOCION,
CHECK(ESTADO='ENTREGADO'  OR ESTADO='SOLICITADO' OR ESTADO='CANCELADO'));

CREATE TABLE CAMION(
MATRICULA VARCHAR2(20) NOT NULL,
DNI VARCHAR2(20),
PRIMARY KEY(MATRICULA),
FOREIGN KEY(DNI) REFERENCES PERSONAL );

CREATE TABLE PUNTODEVENTA(
OID_PUNTODEVENTA NUMBER,
TELEFONO VARCHAR2(20),
DIRECCION VARCHAR2(30),
CADENA VARCHAR2(20),
PRIMARY KEY(OID_PUNTODEVENTA));

CREATE TABLE CAMIONESPUNTODEVENTA(
OID_INTER NUMBER,
OID_PUNTODEVENTA NUMBER,
MATRICULA VARCHAR2(20),
PRIMARY KEY(OID_INTER),
FOREIGN KEY(OID_PUNTODEVENTA)REFERENCES PUNTODEVENTA,
FOREIGN KEY(MATRICULA)REFERENCES CAMION);

CREATE TABLE CAMIONESPEDIDO(
OID_INTER2 NUMBER,
MATRICULA VARCHAR2(20),
OID_PEDIDO NUMBER,
PRIMARY KEY(OID_INTER2), 
FOREIGN KEY (MATRICULA) REFERENCES CAMION,
FOREIGN KEY (OID_PEDIDO) REFERENCES PEDIDO);

CREATE TABLE PRODUCTOPALET(
OID_INTER3 NUMBER,
OID_PALET NUMBER,
OID_PRODUCTO NUMBER,
PRIMARY KEY(OID_INTER3),
FOREIGN KEY (OID_PALET) REFERENCES PALET,
FOREIGN KEY (OID_PRODUCTO) REFERENCES PRODUCTO);

CREATE TABLE PALETPEDIDO(
OID_INTER4 NUMBER,
OID_PEDIDO NUMBER,
OID_PALET NUMBER,
PRIMARY KEY (OID_INTER4),
FOREIGN KEY (OID_PEDIDO) REFERENCES PEDIDO,
FOREIGN KEY (OID_PALET) REFERENCES PALET);

-----FUNCIONES----
----1 CUENTA LOS NUMEROS DE PEDIDOS QUE LLEVA UN CAMION AL DIA PASANDO LA MATRICULA DEL CAMION Y LA FECHA DEL PEDIDO-------
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION NUMPEDIDOSALDIA(
W_MATRICULA IN CAMIONESPEDIDO.MATRICULA%TYPE,
W_FECHA IN VARCHAR2)
RETURN NUMBER IS NUMEROPEDIDOS NUMBER;
BEGIN
SELECT COUNT(*) INTO NUMEROPEDIDOS FROM PEDIDO, CAMIONESPEDIDO
WHERE CAMIONESPEDIDO.OID_PEDIDO=PEDIDO.OID_PEDIDO
AND CAMIONESPEDIDO.MATRICULA=W_MATRICULA AND TO_CHAR(PEDIDO.FECHAPEDIDO, 'DD-MM-YYYY')=W_FECHA;
RETURN NUMEROPEDIDOS;
END NUMPEDIDOSALDIA;
/

------ 2 CALCULAR LA MEDIA DE LOS PRECIOS DEL PRODUCTO QUE TIENEN TIPO FORMATO LITRONA-----
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION MEDIAPRECIOS(
W_PRECIO IN PRODUCTO.PRECIO%TYPE,
W_TIPOFORMATO IN PRODUCTO.TIPOFORMATO%TYPE)
RETURN NUMBER IS DEVUELVEMEDIA NUMBER;
BEGIN
SELECT AVG(PRECIO) INTO DEVUELVEMEDIA FROM PRODUCTO WHERE TIPOFORMATO='LITRONA';
RETURN DEVUELVEMEDIA;
END MEDIAPRECIOS;
/
----FUNCION 3 CON JOIN. DEVUELVE EL PRECIO DEL PALET-----
create or replace FUNCTION PRECIOPALET(
W_OID_PALET IN PALET.OID_PALET%TYPE)

RETURN NUMBER IS PREC NUMBER;
BEGIN
SELECT SUM(PRECIO) INTO PREC FROM PRODUCTO JOIN PRODUCTOPALET ON PRODUCTOPALET.OID_PRODUCTO = PRODUCTO.OID_PRODUCTO AND PRODUCTOPALET.OID_PALET=W_OID_PALET;

RETURN PREC;
END PRECIOPALET;
/


-----FUNCION 4 CON JOIN: CALCULAR CUANTOS PALET LLEVA CADA PEDIDO------
CREATE OR REPLACE FUNCTION NUMPALETSPORPEDIDO (
W_OID_PEDIDO IN PEDIDO.OID_PEDIDO%TYPE)

RETURN NUMBER IS CONT NUMBER;
BEGIN

SELECT COUNT(*) INTO CONT FROM PALET JOIN PALETPEDIDO ON PALETPEDIDO.OID_PALET = PALET.OID_PALET AND PALETPEDIDO.OID_PEDIDO=W_OID_PEDIDO;


RETURN CONT;
END NUMPALETSPORPEDIDO;
/




-- CREACIÓN DE PROCEDIMIENTOS


--1 AÑADE UNA PERSONA A LA TABLA PERSONAL

create or replace PROCEDURE AÑADIR_PERSONAL

(W_DNI IN PERSONAL.DNI%TYPE,
W_NOMBRE IN PERSONAL.NOMBRE%TYPE,
W_APELLIDOS IN PERSONAL.APELLIDOS%TYPE,
W_EMAIL IN PERSONAL.EMAIL%TYPE,
W_TELEFONO IN PERSONAL.TELEFONO%TYPE)
IS
BEGIN
INSERT INTO PERSONAL (DNI,NOMBRE,APELLIDOS,EMAIL,TELEFONO)
VALUES (W_DNI,W_NOMBRE,W_APELLIDOS,W_EMAIL,W_TELEFONO);

END AÑADIR_PERSONAL;
/
--2 CREA UN  PEDIDO

CREATE OR REPLACE PROCEDURE CREAR_PEDIDO
(W_OIDPEDIDO IN PEDIDO.OID_PEDIDO%TYPE,
W_OIDPROMOCION IN PEDIDO.OID_PROMOCION%TYPE,
W_FECHAPEDIDO IN PEDIDO.FECHAPEDIDO%TYPE,
W_FECHAENTREGA IN PEDIDO.FECHAENTREGA%TYPE,
W_TIPODESCUENTO IN PEDIDO.TIPODESCUENTO%TYPE,
W_ESTADO IN PEDIDO.ESTADO%TYPE)
IS
BEGIN
INSERT INTO PEDIDO(OID_PEDIDO,OID_PROMOCION,FECHAPEDIDO,FECHAENTREGA,TIPODESCUENTO,ESTADO)
VALUES (W_OIDPEDIDO,W_OIDPROMOCION,W_FECHAPEDIDO,W_FECHAENTREGA,W_TIPODESCUENTO,W_ESTADO);
END CREAR_PEDIDO;
/
--3-CREAR UN PRODUCTO
CREATE OR REPLACE PROCEDURE AÑADIR_PRODUCTO
(W_OIDPRODUCTO IN PRODUCTO.OID_PRODUCTO%TYPE,
W_TIPOMARCA IN PRODUCTO.TIPOMARCA%TYPE,
W_TIPOFORMATO IN PRODUCTO. TIPOFORMATO%TYPE,
W_PRECIO IN PRODUCTO.PRECIO%TYPE)
IS
BEGIN 
INSERT INTO PRODUCTO(OID_PRODUCTO,TIPOMARCA,TIPOFORMATO,PRECIO)
VALUES(W_OIDPRODUCTO,W_TIPOMARCA,W_TIPOFORMATO,W_PRECIO);
END AÑADIR_PRODUCTO;
/
--4CREAR UN PALET
CREATE OR REPLACE PROCEDURE AÑADIR_PALET
(W_OIDPALET IN PALET.OID_PALET%TYPE
)
IS
BEGIN 
INSERT INTO PALET(OID_PALET)
VALUES(W_OIDPALET);
END AÑADIR_PALET;
/
--5 CREAR PROMOCION--
CREATE OR REPLACE PROCEDURE AÑADIR_PROMOCION
(W_OIDPROMOCION IN PROMOCION.OID_PROMOCION%TYPE,
W_TIPOPROMO IN PROMOCION.TIPOPROMO%TYPE,
W_FECHAINICIOP IN PROMOCION.FECHAINICIOP%TYPE,
W_FECHAFINP IN PROMOCION.FECHAFINP%TYPE)
IS
BEGIN
INSERT INTO PROMOCION (OID_PROMOCION,TIPOPROMO,FECHAINICIOP,FECHAFINP)
VALUES(W_OIDPROMOCION,W_TIPOPROMO,W_FECHAINICIOP,W_FECHAFINP);
END AÑADIR_PROMOCION;
/

---6 CREAR CAMION--
CREATE OR REPLACE PROCEDURE AÑADIR_CAMION
(W_MATRICULA IN CAMION.MATRICULA%TYPE,
W_DNI IN CAMION.DNI%TYPE)
IS
BEGIN
INSERT INTO CAMION (MATRICULA,DNI)
VALUES(W_MATRICULA,W_DNI);
END AÑADIR_CAMION;
/
----7 CREAR PUNTO DE VENTA---
CREATE OR REPLACE PROCEDURE AÑADIR_PUNTODEVENTA
(W_OIDPUNTODEVENTA IN PUNTODEVENTA.OID_PUNTODEVENTA%TYPE,
W_TELEFONO IN PUNTODEVENTA.TELEFONO%TYPE,
W_DIRECCION IN PUNTODEVENTA.DIRECCION%TYPE,
W_CADENA IN PUNTODEVENTA.CADENA%TYPE)
IS
BEGIN
INSERT INTO PUNTODEVENTA(OID_PUNTODEVENTA,TELEFONO,DIRECCION,CADENA)
VALUES(W_OIDPUNTODEVENTA,W_TELEFONO,W_DIRECCION,W_CADENA);
END AÑADIR_PUNTODEVENTA;

/
----8 CREAR CAMIONESPUNTODEVENTA--
CREATE OR REPLACE PROCEDURE AÑADIR_CAMIONESPUNTODEVENTA
(W_OIDINTER IN CAMIONESPUNTODEVENTA.OID_INTER%TYPE,
W_OIDPUNTODEVENTA IN CAMIONESPUNTODEVENTA.OID_PUNTODEVENTA%TYPE,
W_OIDMATRICULA IN CAMIONESPUNTODEVENTA.MATRICULA%TYPE)
IS
BEGIN
INSERT INTO CAMIONESPUNTODEVENTA(OID_INTER,OID_PUNTODEVENTA,MATRICULA)
VALUES(W_OIDINTER,W_OIDPUNTODEVENTA,W_OIDMATRICULA);
END AÑADIR_CAMIONESPUNTODEVENTA;
/
-----9 CREAR CAMIONESPEDIDO--
CREATE OR REPLACE PROCEDURE AÑADIR_CAMIONESPEDIDO
(W_OIDINTER2 IN CAMIONESPEDIDO.OID_INTER2%TYPE,
W_MATRICULA IN CAMIONESPEDIDO.MATRICULA%TYPE,
W_OIDPEDIDO IN CAMIONESPEDIDO.OID_PEDIDO%TYPE)
IS
BEGIN
INSERT INTO CAMIONESPEDIDO (OID_INTER2,MATRICULA,OID_PEDIDO)
VALUES (W_OIDPEDIDO,W_MATRICULA,W_OIDPEDIDO);
END AÑADIR_CAMIONESPEDIDO;
/
---- 10 CREAR PRODUCTOPALET
CREATE OR REPLACE PROCEDURE AÑADIR_PRODUCTOPALET
(W_OIDINTER3 IN PRODUCTOPALET.OID_INTER3%TYPE,
W_OIDPALET IN PRODUCTOPALET.OID_PALET%TYPE,
W_OIDPRODUCTO IN PRODUCTOPALET.OID_PRODUCTO%TYPE)
IS
BEGIN
INSERT INTO PRODUCTOPALET (OID_INTER3, OID_PALET,OID_PRODUCTO)
VALUES (W_OIDINTER3,W_OIDPALET,W_OIDPRODUCTO);
END AÑADIR_PRODUCTOPALET;
/
---11 CREAR PALETPEDIDO--
CREATE OR REPLACE PROCEDURE AÑADIR_PALETPEDIDO
(W_OIDINTER4 IN PALETPEDIDO.OID_INTER4%TYPE,
W_OIDPEDIDO IN PALETPEDIDO.OID_PEDIDO%TYPE,
W_OIDPALET IN PALETPEDIDO.OID_PALET%TYPE)
IS
BEGIN
INSERT INTO PALETPEDIDO (OID_INTER4, OID_PEDIDO, OID_PALET)
VALUES (W_OIDINTER4, W_OIDPEDIDO, W_OIDPALET);
END AÑADIR_PALETPEDIDO;
/


-- 1 PROCEDIMIENTO CON CURSOR Y GROUP BY: NUMERO DE PEDIDOS QUE TRANSPORTA CADA CAMION
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE NUMERO_PEDIDOS_CAMION IS
BEGIN
DECLARE
CONTADOR1 NUMBER;
CURSOR C1 IS SELECT MATRICULA,COUNT(*) AS CONTADOR1 FROM CAMIONESPEDIDO GROUP BY MATRICULA ORDER BY 1;
REGISTRO1 C1%ROWTYPE; 
BEGIN
OPEN C1;
LOOP
  FETCH C1 INTO REGISTRO1;
  EXIT WHEN C1%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE('EL NUMERO DE PEDIDOS QUE TRANSPORTA EL CAMION '||REGISTRO1.MATRICULA||' SON: '||REGISTRO1.CONTADOR1);
  END LOOP;
CLOSE C1;
END;
END;

/

---2. PROCEDIMIENTO CON CURSOR Y JOIN: tabla conjunta de un pedido junto con su promocion 'VALORAÑADIDO' --
SET SERVEROUTPUT ON; 
CREATE OR REPLACE PROCEDURE PEDIDOPROMO IS
BEGIN
DECLARE 
CURSOR C2 IS SELECT * FROM PEDIDO INNER JOIN PROMOCION ON PROMOCION.OID_PROMOCION = PEDIDO.OID_PROMOCION WHERE  PROMOCION.TIPOPROMO='VALORAÑADIDO';
REGISTRO2 C2%ROWTYPE;
BEGIN
OPEN C2;
LOOP
  FETCH C2 INTO REGISTRO2;
  EXIT WHEN C2%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE(' LOS PEDIDOS CON PROMOCION '||REGISTRO2.TIPOPROMO||' SON: '||REGISTRO2.OID_PEDIDO );
 
  END LOOP;
CLOSE C2;
END;
END;
/

---3 PROCEDIMIENTO CON CURSOR Y JOIN: crear tabla  de un PRODUCTOPALET con prodcuto cuyo tipo marca sea 'CRUZCAMPO'
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE PALETPRODUCTO IS
BEGIN
DECLARE
CURSOR C3 IS SELECT * FROM PRODUCTOPALET INNER JOIN PRODUCTO ON PRODUCTO.OID_PRODUCTO= PRODUCTOPALET.OID_PRODUCTO WHERE PRODUCTO.TIPOMARCA='CRUZCAMPO';
REGISTRO3 C3%ROWTYPE;
BEGIN
OPEN C3;
LOOP
  FETCH C3 INTO REGISTRO3;
  EXIT WHEN C3%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE(' LOS PRODUCTOS CON TIPOMARCA '||REGISTRO3.TIPOMARCA||' SON: '||REGISTRO3.OID_PALET );
  END LOOP;
CLOSE C3;
END;
END;

/
---4 PROCEDIMIENTO CON CURSOR Y JOIN: crear una tabla conjunta en la que aparezcan los atributos TIPOMARCA,TIPOFORMATO,PRECIO, OID_PRODUCTO 
---- siendo el precio del palet 120€

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE TABLACONJUNTAPRECIO IS
BEGIN
DECLARE CURSOR C4 IS SELECT P.TIPOMARCA, P.TIPOFORMATO,P.PRECIO,PR.OID_PRODUCTO
FROM PRODUCTO P JOIN PRODUCTOPALET PR ON P.OID_PRODUCTO = PR.OID_PRODUCTO
WHERE P.PRECIO='120';
REGISTRO4 C4%ROWTYPE;
BEGIN
OPEN C4;
LOOP
  FETCH C4 INTO REGISTRO4;
  EXIT WHEN C4%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE(' LOS PALET QUE CUESTAN '||REGISTRO4.PRECIO||' SON: '||REGISTRO4.OID_PRODUCTO );
  END LOOP;
CLOSE C4;
END;
END;
/

----5. PROCEDIMIENTO CON CURSOR Y JOIN:crear una tabla en la que aparezcan los camiones de CAMIONESPUNTOVENTA que vayan a los PUNTOSDEVENTA SUPERSOL

SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE CADENAPUNTOVENTA IS
BEGIN
DECLARE CURSOR C5 IS SELECT C.OID_INTER,C.OID_PUNTODEVENTA,C.MATRICULA,PV.TELEFONO,PV.DIRECCION,PV.CADENA
FROM CAMIONESPUNTODEVENTA C JOIN PUNTODEVENTA PV ON C.OID_PUNTODEVENTA = PV.OID_PUNTODEVENTA
WHERE PV.CADENA='SUPERSOL';
REGISTRO5 C5%ROWTYPE;
BEGIN
OPEN C5;
LOOP
  FETCH C5 INTO REGISTRO5;
  EXIT WHEN C5%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE(' LOS CAMIONES QUE VAN AL '||REGISTRO5.CADENA||' SON: '||REGISTRO5.MATRICULA );
  END LOOP;
CLOSE C5;
END;
END;
/
----6.PROCEDIMIENTO CON CURSOR Y GROUP BY TIPODESCUENTO QUE PUEDA TENER UN PEDIDO
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE TIPODESCPEDIDOS IS
BEGIN
DECLARE
CONTADOR2 NUMBER;
CURSOR C6 IS SELECT TIPODESCUENTO,COUNT(*) AS CONTADOR2 FROM PEDIDO GROUP BY TIPODESCUENTO ORDER BY 1;
REGISTRO6 C6%ROWTYPE; 
BEGIN
OPEN C6;
LOOP
  FETCH C6 INTO REGISTRO6;
  EXIT WHEN C6%NOTFOUND;
  DBMS_OUTPUT.PUT_LINE('LOS TIPOS DE DESCUENTO DE UN PEDIDO '||REGISTRO6.TIPODESCUENTO||' SON: '||REGISTRO6.CONTADOR2);
  END LOOP;
CLOSE C6;
END;
END;

/
--PROCEDIMIENTO QUE MODIFICA EL ESTADO DEL PEDIDO

CREATE OR REPLACE PROCEDURE MODIFICAESTADO (
W_CODPEDIDO IN PEDIDO.OID_PEDIDO%TYPE, 
W_ESTADO IN PEDIDO.ESTADO%TYPE) 
IS
BEGIN
UPDATE PEDIDO SET ESTADO = W_ESTADO 
WHERE OID_PEDIDO IN
(SELECT OID_PEDIDO FROM PEDIDO WHERE OID_PEDIDO=W_CODPEDIDO);
COMMIT WORK;
END MODIFICAESTADO;
/


--CREACIÓN DE SECUENCIAS


CREATE SEQUENCE SEC_PALET INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_PEDIDO INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_PRODUCTO INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_PROMOCION INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_PUNTODEVENTA INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_INTERMEDIA INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_INTER2 INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_INTER3 INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;
CREATE SEQUENCE SEC_INTER4 INCREMENT BY 1 START WITH 0001 MAXVALUE 9999 MINVALUE 0001;


--CREACIÓN DE TRIGGERS

--1- UN CAMIÓN NO PUEDE LLEVAR MÁS DE 5 PEDIDOS EN 1 DÍA

CREATE OR REPLACE TRIGGER MAX_PEDIDO_DIA 
BEFORE INSERT ON CAMIONESPEDIDO FOR EACH ROW 
DECLARE FEC DATE;
NUN INTEGER;
BEGIN
SELECT FECHAENTREGA INTO FEC FROM PEDIDO WHERE OID_PEDIDO= :NEW.OID_PEDIDO;
SELECT COUNT(OID_PEDIDO) INTO NUN FROM PEDIDO NATURAL JOIN CAMIONESPEDIDO WHERE FEC=FECHAENTREGA AND :NEW.MATRICULA=MATRICULA;
  IF NUN>=5
  THEN 
  raise_application_error(-20600,'Se ha superado el número máximo de pedidos');
  END IF;
END;
/


--2.- UN PALET NO PUEDE LLEVAR MÁS DE 10 PRODUCTOS

CREATE OR REPLACE TRIGGER MAXIMO_PRODUCTO_PALET 
BEFORE INSERT ON PRODUCTOPALET FOR EACH ROW
DECLARE NUN INTEGER;
BEGIN

SELECT COUNT(OID_PRODUCTO) INTO NUN FROM PRODUCTO NATURAL JOIN PRODUCTOPALET WHERE :NEW.OID_PALET=OID_PALET;
  IF NUN>=10
  THEN 
  raise_application_error(-20600,'Se ha superado el número máximo de productos');
  END IF;
END;
/

--3.- UN PEDIDO NO PUEDE CANCELARSE SI HA PASADO UN DÍA TRAS SU SOLICITUD

CREATE OR REPLACE TRIGGER CANCELACION
BEFORE UPDATE ON PEDIDO FOR EACH ROW 
WHEN (NEW.ESTADO='CANCELADO' AND SYSDATE>(OLD.FECHAPEDIDO+1)) 
BEGIN
  
  RAISE_APPLICATION_ERROR(-20600,'NO SE PUEDE CANCELAR UN PEDIDO TRANSCURRIDO UN DIA DESDE SU SOLICITUD');
  
END;
/
--UPDATE PEDIDO(5,'6','05-03-2016','08-03-2016','PRONTO PAGO','SOLICITADO');

/*--4.- BORRA EL PEDIDO SI EL ESTADO DE ESTE ES CANCELADO

CREATE OR REPLACE TRIGGER BORRAPEDIDOCAMION 
BEFORE DELETE ON CAMIONESPEDIDO FOR EACH ROW
DECLARE ESTADOP  VARCHAR2(20);

BEGIN
SELECT COUNT(ESTADO) INTO ESTADOP FROM PEDIDO NATURAL JOIN CAMIONESPEDIDO WHERE :NEW.OID_PEDIDO=OID_PEDIDO;
    IF ESTADOP='CANCELADO'
  THEN 
  raise_application_error(-20600,'NO SE LLEVA UN PRODUCTO QUE SE HA CANCELADO');
  END IF;
END;
/
*/





--INSERCIÓN DE TUPLAS EN LAS TABLAS
INSERT INTO PERSONAL VALUES ('20067658C','ALVARO','GAGO FABERO','ALVARO-GAGO-13@HOTMAIL.COM','711762049');
INSERT INTO PERSONAL VALUES ('20123498A','CECILIA','JARAQUEMADA GIMENEZ','CECI@HOTMAIL.COM','627264345');
INSERT INTO PERSONAL VALUES ('34585676Z','BRAULIO','ORTIZ DUQUE','ELBRAU@GMAIL.COM','674829629');
INSERT INTO PERSONAL VALUES ('I9465537S','PAULA','PUERTO PINO','PAULI_33@HOTMAIL.COM','564762049');

EXECUTE AÑADIR_PERSONAL ('23397869A','LUIS','LOPEZ LUGO','TRIPLEL@GMAIL.COM','697542369');
EXECUTE AÑADIR_PERSONAL ('23564869A','ALFREDO','ALFEREZ ALTOZANO','ALALAL@GMAIL.COM','699685769');




--INSERT INTO PRODUCTO VALUES (SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','BOTELLIN 1/5','120');






EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');










EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');

EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');

EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');

EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'HEINEKEN','LITRONA','120');




EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');



EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LATA','200');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');


EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'AMSTEL','LATA','140');




EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');

EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'DESPERADOS','BOTELLIN 1/3','140');





EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');
EXECUTE AÑADIR_PRODUCTO(SEC_PRODUCTO.NEXTVAL,'CRUZCAMPO','LITRONA','120');











EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)
EXECUTE AÑADIR_PALET(SEC_PALET.NEXTVAL)

INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'CRUZADA','01-06-2015','01-07-2015');
INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'VALORAÑADIDO','11-04-2016','17-04-2016');
INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'VALORAÑADIDO','03-12-2015','07-01-2016');
INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'OFERTA','01-03-2016','30-03-2016');
INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'OFERTA','02-03-2016','30-03-2016');
INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'OFERTA','30-03-2016','01-04-2016');
INSERT INTO PROMOCION VALUES(SEC_PROMOCION.NEXTVAL,'OFERTA','01-04-2016','05-04-2016');

EXECUTE AÑADIR_PROMOCION(SEC_PROMOCION.NEXTVAL,'OFERTA','01-04-2016','05-04-2016');
EXECUTE AÑADIR_PROMOCION(SEC_PROMOCION.NEXTVAL,'CRUZADA','20-04-2016','25-04-2016');
EXECUTE AÑADIR_PROMOCION(SEC_PROMOCION.NEXTVAL,'VALORAÑADIDO','13-05-2016','18-05-2016');



INSERT INTO PEDIDO VALUES(SEC_PEDIDO.NEXTVAL,'3','03-03-2015','04-03-2015','PRONTO PAGO','ENTREGADO');
INSERT INTO PEDIDO VALUES(SEC_PEDIDO.NEXTVAL,'1','02-01-2016','05-01-2016','NULL','ENTREGADO');
INSERT INTO PEDIDO VALUES(SEC_PEDIDO.NEXTVAL,'2','03-01-2016','6-01-2016', 'PRONTO PAGO','ENTREGADO');
INSERT INTO PEDIDO VALUES(SEC_PEDIDO.NEXTVAL,'4','04-02-2016','7-03-2016', 'PRONTO PAGO','ENTREGADO');
INSERT INTO PEDIDO VALUES(SEC_PEDIDO.NEXTVAL,'6','05-03-2016','8-03-2016', 'PRONTO PAGO','ENTREGADO');

EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','NULL','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','NULL','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','PRONTO PAGO','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','PRONTO PAGO','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','PRONTO PAGO','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','NULL','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','NULL','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','05-03-2016','8-03-2016','NULL','ENTREGADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','28-05-2016','30-05-2016','NULL','SOLICITADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','28-05-2016','30-05-2016','NULL','SOLICITADO');
EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','30-05-2016','10-06-2016','NULL','SOLICITADO');
--EXECUTE CREAR_PEDIDO (SEC_PEDIDO.NEXTVAL,'7','31-05-2016','10-06-2016','NULL','SOLICITADO');




INSERT INTO CAMION VALUES('1234AA','20067658C');
INSERT INTO CAMION VALUES('1234AB','34585676Z');
INSERT INTO CAMION VALUES('1234AC','I9465537S');
INSERT INTO CAMION VALUES('5641CJG','I9465537S');

EXECUTE AÑADIR_CAMION ('1234AD','20067658C');
EXECUTE AÑADIR_CAMION ('1234AE','34585676Z');



INSERT INTO PUNTODEVENTA VALUES (SEC_PUNTODEVENTA.NEXTVAL,'954461832','AVENIDA REINA MERCEDES 32','SUPERSOL');
INSERT INTO PUNTODEVENTA VALUES (SEC_PUNTODEVENTA.NEXTVAL,'954889965','CALLE BAMI 12','EL JAMON');
INSERT INTO PUNTODEVENTA VALUES (SEC_PUNTODEVENTA.NEXTVAL,'954314459','RONDA DEL TAMARGUILLO SN','ALCAMPO');

EXECUTE AÑADIR_PUNTODEVENTA(SEC_PUNTODEVENTA.NEXTVAL,'954461845','CALLE SOL 23','MERCADONA');
EXECUTE AÑADIR_PUNTODEVENTA(SEC_PUNTODEVENTA.NEXTVAL,'954311845','CALLE MONZON 1','SUPERSOL');
EXECUTE AÑADIR_PUNTODEVENTA(SEC_PUNTODEVENTA.NEXTVAL,'954463445','CALLE CASTILLA 21','MERCADONA');




INSERT INTO CAMIONESPUNTODEVENTA VALUES(SEC_INTERMEDIA.NEXTVAL,'1','1234AC');
INSERT INTO CAMIONESPUNTODEVENTA VALUES(SEC_INTERMEDIA.NEXTVAL,'2','1234AA');
INSERT INTO CAMIONESPUNTODEVENTA VALUES(SEC_INTERMEDIA.NEXTVAL,'3','1234AA');
INSERT INTO CAMIONESPUNTODEVENTA VALUES(SEC_INTERMEDIA.NEXTVAL,'1','1234AA');
INSERT INTO CAMIONESPUNTODEVENTA VALUES(SEC_INTERMEDIA.NEXTVAL,'1','1234AA');


EXECUTE AÑADIR_CAMIONESPUNTODEVENTA(SEC_INTERMEDIA.NEXTVAL,'2','1234AA');
EXECUTE AÑADIR_CAMIONESPUNTODEVENTA(SEC_INTERMEDIA.NEXTVAL,'1','1234AA');
EXECUTE AÑADIR_CAMIONESPUNTODEVENTA(SEC_INTERMEDIA.NEXTVAL,'3','1234AA');
EXECUTE AÑADIR_CAMIONESPUNTODEVENTA(SEC_INTERMEDIA.NEXTVAL,'4','1234AA');
EXECUTE AÑADIR_CAMIONESPUNTODEVENTA(SEC_INTERMEDIA.NEXTVAL,'5','1234AA');
EXECUTE AÑADIR_CAMIONESPUNTODEVENTA(SEC_INTERMEDIA.NEXTVAL,'6','1234AA');


EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','1');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AB','2');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AC','3');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AD','4');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AE','5');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','6');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','7');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','8');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','9');
EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','10');


--PARA QUE SALTE EL TRIGGER EJECUTAR ESTE

--EXECUTE AÑADIR_CAMIONESPEDIDO(SEC_INTER2.NEXTVAL,'1234AA','11');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','1');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','2');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','3');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','4');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','5');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','6');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','7');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','8');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','9');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','10');
--PARA QUE SALTE EL SEGUNDO TRIGGER
--EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'1','11');




EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','11');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','12');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','13');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','14');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','15');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','16');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','17');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','18');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','19');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'2','20');



EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','21');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','22');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','23');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','24');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','25');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','26');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','27');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','28');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','29');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'3','30');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','31');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','32');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','33');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','34');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','35');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','36');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','37');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','38');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','39');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'4','40');


EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','41');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','42');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','43');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','44');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','45');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','46');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','47');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','48');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','49');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'5','50');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','51');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','52');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','53');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','54');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','55');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','56');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','57');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','58');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','59');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'6','60');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','61');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','62');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','63');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','64');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','65');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','66');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','67');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','68');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','69');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'7','70');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','71');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','72');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','73');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','74');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','75');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','76');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','77');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','78');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','79');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'8','80');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','81');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','82');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','83');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','84');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','85');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','86');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','87');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','88');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','89');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'9','90');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','91');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','92');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','93');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','94');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','95');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','96');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','97');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','98');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','99');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'10','100');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','101');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','102');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','103');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','104');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','105');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','106');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','107');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','108');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','109');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'11','110');

EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','111');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','112');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','113');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','114');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','115');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','116');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','117');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','118');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','119');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'12','120');


EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','121');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','122');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','123');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','124');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','125');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','126');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','127');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','128');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','129');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'13','130');


EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','131');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','132');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','133');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','134');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','135');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','136');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','137');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','138');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','139');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'14','140');



EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','141');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','142');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','143');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','144');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','145');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','146');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','147');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','148');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','149');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'15','150');


EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','151');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','152');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','153');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','154');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','155');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','156');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','157');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','158');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','159');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'16','160');



EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','161');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','162');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','163');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','164');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','165');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','166');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','167');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','168');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','169');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'17','170');



EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','171');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','172');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','173');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','174');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','175');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','176');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','177');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','178');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','179');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'18','180');



EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','181');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','182');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','183');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','184');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','185');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','186');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','187');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','188');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','189');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'19','190');



EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','191');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','192');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','193');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','194');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','195');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','196');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','197');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','198');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','199');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'20','200');




EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','201');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','202');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','203');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','204');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','205');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','206');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','207');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','208');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','209');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'21','210');


EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','211');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','212');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','213');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','214');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','215');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','216');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','217');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','218');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','219');
EXECUTE AÑADIR_PRODUCTOPALET(SEC_INTER3.NEXTVAL,'22','220');








EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'1','1');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'1','2');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'1','3');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'2','4');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'2','5');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'3','6');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'3','7');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'3','8');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'3','9');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'4','10');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'4','11');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'5','12');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'5','13');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'5','14');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'5','15');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'5','16');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'5','17');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'8','18');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'9','19');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'10','20');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'10','21');
EXECUTE AÑADIR_PALETPEDIDO(SEC_INTER4.NEXTVAL,'10','22');





EXECUTE NUMERO_PEDIDOS_CAMION;
EXECUTE PEDIDOPROMO;
EXECUTE PALETPRODUCTO;
EXECUTE TABLACONJUNTAPRECIO;
EXECUTE CADENAPUNTOVENTA;
EXECUTE TIPODESCPEDIDOS;


----CONSULTAS----
-- CONSULTAS 
--- 1. tabla conjunta de un pedido junto con su promocion 'VALORAÑADIDO' --

SELECT * FROM PEDIDO INNER JOIN PROMOCION ON PROMOCION.OID_PROMOCION = PEDIDO.OID_PROMOCION WHERE  PROMOCION.TIPOPROMO='VALORAÑADIDO';

-- 2 crear tabla  de un PRODUCTOPALET con prodcuto cuyo tipo marca sea 'CRUZCAMPO'
SELECT * FROM PRODUCTOPALET INNER JOIN PRODUCTO ON PRODUCTO.OID_PRODUCTO= PRODUCTOPALET.OID_PRODUCTO WHERE PRODUCTO.TIPOMARCA='CRUZCAMPO';

---- 3 crear una tabla conjunta en la que aparezcan los atributos TIPOMARCA, TIPOFORMATO,PRECIO,OID_PRODUCTO
---- siendo el precio del palet 120€
SELECT P.TIPOMARCA, P.TIPOFORMATO,P.PRECIO,PR.OID_PRODUCTO
FROM PRODUCTO P JOIN PRODUCTOPALET PR ON P.OID_PRODUCTO = PR.OID_PRODUCTO
WHERE P.PRECIO='120';

----4. crear una tabla en la que aparezcan los camiones de CAMIONESPUNTOVENTA que vayan a los PUNTOSDEVENTA SUPERSOL
SELECT C.OID_INTER,C.OID_PUNTODEVENTA,C.MATRICULA,PV.TELEFONO,PV.DIRECCION,PV.CADENA
FROM CAMIONESPUNTODEVENTA C JOIN PUNTODEVENTA PV ON C.OID_PUNTODEVENTA = PV.OID_PUNTODEVENTA
WHERE PV.CADENA='SUPERSOL';

----5. CUENTA EL NUMERO DE VECES QUE APARECE UNA MATRICULA----
SELECT MATRICULA,COUNT(*) AS CONTADOR1 FROM CAMIONESPEDIDO GROUP BY MATRICULA ORDER BY 1;

----6. CUENTA EL NUMERO DE VECES QUE APARECE CADA TIPO DE DESCUENTO----
SELECT TIPODESCUENTO,COUNT(*) AS CONTADOR2 FROM PEDIDO GROUP BY TIPODESCUENTO ORDER BY 1;



--PRUEBA DE FUNCIONES

--PRUEBA DE LA FUNCION 1----
BEGIN
DBMS_OUTPUT.PUT_LINE('EL NUMERO DE PEDIDOS ES: '||NUMPEDIDOSALDIA('1234AA','05-03-2016'));
END;
/
--PRUEBA DE LA FUNCION 2-----
BEGIN
DBMS_OUTPUT.PUT_LINE('LA MEDIA DEL PRECIO DE LOS PRODUCTOS CON TIPO FORMATO LITRONA ES: '||MEDIAPRECIOS('120','BOTELLINES 1/5'));
END;
/
---PRUEBA DE LA FUNCION 3----
BEGIN
DBMS_OUTPUT.PUT_LINE('EL PRECIO DE LOS PALET CON CODIGO PALET 1: '||PRECIOPALET('1'));
END;
/
----PRUEBA DE LA FUNCION 4----
BEGIN
DBMS_OUTPUT.PUT_LINE('EL NUMERO DE PALETS QUE LLEVA UN PEDIDO ES: '||NUMPALETSPORPEDIDO('2'));
END;
/
--PARA QUE SALTE EL TERCER TRIGGER

SELECT * FROM PEDIDO;
UPDATE PEDIDO
SET ESTADO = 'CANCELADO'
WHERE OID_PEDIDO = 15;
